//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MNSSubscribe.ClickMNS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MNSProductReqSoapBinding", Namespace="http://service.soap.mns.huawei.com")]
    public partial class MNSProductReqService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback subscribeMNSProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback unsubscribeMNSProductOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MNSProductReqService() {
            this.Url = global::MNSSubscribe.Properties.Settings.Default.MNSSubscribe_ClickMNS_MNSProductReqService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event subscribeMNSProductCompletedEventHandler subscribeMNSProductCompleted;
        
        /// <remarks/>
        public event unsubscribeMNSProductCompletedEventHandler unsubscribeMNSProductCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.soap.mns.huawei.com", ResponseNamespace="http://service.soap.mns.huawei.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("subscribeMNSProductReturn")]
        public SubscribeMNSProductRsp subscribeMNSProduct(ProductSubscribeReq in0) {
            object[] results = this.Invoke("subscribeMNSProduct", new object[] {
                        in0});
            return ((SubscribeMNSProductRsp)(results[0]));
        }
        
        /// <remarks/>
        public void subscribeMNSProductAsync(ProductSubscribeReq in0) {
            this.subscribeMNSProductAsync(in0, null);
        }
        
        /// <remarks/>
        public void subscribeMNSProductAsync(ProductSubscribeReq in0, object userState) {
            if ((this.subscribeMNSProductOperationCompleted == null)) {
                this.subscribeMNSProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubscribeMNSProductOperationCompleted);
            }
            this.InvokeAsync("subscribeMNSProduct", new object[] {
                        in0}, this.subscribeMNSProductOperationCompleted, userState);
        }
        
        private void OnsubscribeMNSProductOperationCompleted(object arg) {
            if ((this.subscribeMNSProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.subscribeMNSProductCompleted(this, new subscribeMNSProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://service.soap.mns.huawei.com", ResponseNamespace="http://service.soap.mns.huawei.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("unsubscribeMNSProductReturn")]
        public UnsubscribeMNSProductRsp unsubscribeMNSProduct(ProductUnSubscribeReq in0) {
            object[] results = this.Invoke("unsubscribeMNSProduct", new object[] {
                        in0});
            return ((UnsubscribeMNSProductRsp)(results[0]));
        }
        
        /// <remarks/>
        public void unsubscribeMNSProductAsync(ProductUnSubscribeReq in0) {
            this.unsubscribeMNSProductAsync(in0, null);
        }
        
        /// <remarks/>
        public void unsubscribeMNSProductAsync(ProductUnSubscribeReq in0, object userState) {
            if ((this.unsubscribeMNSProductOperationCompleted == null)) {
                this.unsubscribeMNSProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunsubscribeMNSProductOperationCompleted);
            }
            this.InvokeAsync("unsubscribeMNSProduct", new object[] {
                        in0}, this.unsubscribeMNSProductOperationCompleted, userState);
        }
        
        private void OnunsubscribeMNSProductOperationCompleted(object arg) {
            if ((this.unsubscribeMNSProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unsubscribeMNSProductCompleted(this, new unsubscribeMNSProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.service.soap.mns.huawei.com")]
    public partial class ProductSubscribeReq {
        
        private string mSISDNField;
        
        private System.Nullable<int> channelIDField;
        
        private string operDescField;
        
        private string operTimeField;
        
        private string productIDField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string MSISDN {
            get {
                return this.mSISDNField;
            }
            set {
                this.mSISDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> channelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string operDesc {
            get {
                return this.operDescField;
            }
            set {
                this.operDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string operTime {
            get {
                return this.operTimeField;
            }
            set {
                this.operTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.service.soap.mns.huawei.com")]
    public partial class UnsubscribeMNSProductRsp {
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://pojo.service.soap.mns.huawei.com")]
    public partial class Result {
        
        private string resultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://request.service.soap.mns.huawei.com")]
    public partial class ProductUnSubscribeReq {
        
        private string mSISDNField;
        
        private System.Nullable<int> channelIDField;
        
        private string operDescField;
        
        private string operTimeField;
        
        private string productIDField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string MSISDN {
            get {
                return this.mSISDNField;
            }
            set {
                this.mSISDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> channelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string operDesc {
            get {
                return this.operDescField;
            }
            set {
                this.operDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string operTime {
            get {
                return this.operTimeField;
            }
            set {
                this.operTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://response.service.soap.mns.huawei.com")]
    public partial class SubscribeMNSProductRsp {
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void subscribeMNSProductCompletedEventHandler(object sender, subscribeMNSProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class subscribeMNSProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal subscribeMNSProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubscribeMNSProductRsp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubscribeMNSProductRsp)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void unsubscribeMNSProductCompletedEventHandler(object sender, unsubscribeMNSProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unsubscribeMNSProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unsubscribeMNSProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnsubscribeMNSProductRsp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnsubscribeMNSProductRsp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591